# Generated by Django 3.2.6 on 2022-05-06 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='breakfast')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='dinner')),
            ],
        ),
        migrations.CreateModel(
            name='LunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='lunch')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('type_in_arabic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='snacks')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_in_arabic', models.CharField(default='', max_length=50)),
                ('imageURL', models.ImageField(null=True, upload_to='recipes')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('video', models.CharField(max_length=500, null=True)),
                ('video_in_arabic', models.CharField(max_length=500, null=True)),
                ('ingridents', models.TextField(default='')),
                ('ingridents_in_arabic', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
