# Generated by Django 4.0.5 on 2022-06-17 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='breakfast')),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='dinner')),
            ],
        ),
        migrations.CreateModel(
            name='LunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='lunch')),
            ],
        ),
        migrations.CreateModel(
            name='RecipesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('type_in_arabic', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SnacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='snacks')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='user')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_in_arabic', models.CharField(default='', max_length=50)),
                ('imageURL', models.ImageField(null=True, upload_to='recipes')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('type_in_arabic', models.CharField(max_length=100, null=True)),
                ('calories', models.IntegerField(null=True)),
                ('video', models.CharField(max_length=500, null=True)),
                ('video_in_arabic', models.CharField(max_length=500, null=True)),
                ('ingridents', models.TextField(default='')),
                ('ingridents_in_arabic', models.TextField(default='')),
                ('time_taken', models.TimeField(null=True)),
                ('directions', models.TextField(default='')),
                ('directions_in_arabic', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                
            ],
        ),
    ]
