# Generated by Django 3.2.6 on 2022-05-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='RecipesTypes',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='type_in_arabic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
