# Generated by Django 3.2.6 on 2021-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
