# Generated by Django 3.2.6 on 2021-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='imageURL',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
