# Generated by Django 3.2.6 on 2022-05-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220517_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='time_taken',
            field=models.TimeField(null=True),
        ),
    ]
