# Generated by Django 3.2.6 on 2021-10-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipemodel_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='imageURL',
            field=models.ImageField(null=True, upload_to='recipes'),
        ),
    ]
