# Generated by Django 3.2.6 on 2022-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recipemodel_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakfastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='breakfast')),
            ],
        ),
        migrations.CreateModel(
            name='DinnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='dinner')),
            ],
        ),
        migrations.CreateModel(
            name='LunchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='lunch')),
            ],
        ),
        migrations.CreateModel(
            name='SnacksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.ImageField(null=True, upload_to='snacks')),
            ],
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingridents',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='video',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
