# Generated by Django 3.2.6 on 2021-10-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationImage',
        ),
        migrations.DeleteModel(
            name='userToken',
        ),
    ]
